sonar.projectKey=ellaisys_aws-cognito
sonar.organization=ellaisys

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=aws-cognito
sonar.projectVersion=1.3.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src
sonar.tests=tests

# Scan scope
sonar.scanner.scanAll=false

# Exclusions from scanning
sonar.exclusions=**/tests/**,**/database/migrations/**,**/database/factories/**,**/database/seeders/**,**/*.yml,**/*.md,**/*.json,**/*.lock,**/*.xml,**/*.txt,**/*.log,**/*.zip

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Forces the analysis step to poll your SonarQube instance until the
# Quality Gate status is available
sonar.qualitygate.wait=true

# Path for code coverage and test execution reports
sonar.php.coverage.reportPaths=build/coverage/clover.xml
sonar.php.tests.reportPath=build/reports/junit.xml

# Exclude files and folders from duplicate code analysis
sonar.cpd.exclusions=database/migrations/**/*
